services:
  - type: web
    name: genie-ai-backend
    env: node
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: OPENAI_API_KEY
        sync: false
    plan: free
    region: oregon
    # Remove rootDirectory to use the project root
